# Generated by Django 3.2.6 on 2021-09-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='user',
            new_name='user_seminar_table',
        ),
        migrations.AddField(
            model_name='seminar',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
