# Generated by Django 3.2.6 on 2021-09-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20210913_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='dropped_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
