# Generated by Django 3.2.6 on 2021-09-14 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seminar', '0003_userseminar_dropped_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='user_seminar_table',
        ),
        migrations.AddField(
            model_name='userseminar',
            name='seminar',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_seminar_table', to='seminar.seminar'),
        ),
        migrations.AddField(
            model_name='userseminar',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_seminar_table', to=settings.AUTH_USER_MODEL),
        ),
    ]
