# Generated by Django 3.2.6 on 2021-09-15 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_auto_20210914_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='count',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seminar',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
