# Generated by Django 3.2.6 on 2021-09-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210913_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='seminar',
            new_name='user_seminar_table',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='instructor',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user', to='user.instructorprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='participant',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user', to='user.participantprofile'),
        ),
    ]
