name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-django-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python manage.py test
        working-directory: ./waffle_backend
