name: Django CI

# action을 실행할 조건
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: 'waffle_backend_2'
          MYSQL_USER: 'waffle-backend'
          MYSQL_PASSWORD: 'seminar'
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r waffle_backend/requirements.txt

    - name: Run Tests
      run: python manage.py test
      working-directory: ./waffle_backend
      env:
        DBENGINE: django.db.backends.mysql
        DBNAME: waffle_backend_2
        DBUSER: waffle-backend
        DBPASSWORD: seminar
        DBHOST: 127.0.0.1
        DBPORT: 3306
        SYSTEM_ENV: GITHUB_WORKFLOW
